export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const ACCESS_HISTORY_GET = 'ACCESS_HISTORY_GET';
export const ACCESS_HISTORY_GET_SUCCESS = 'ACCESS_HISTORY_GET_SUCCESS';
export const ACCESS_HISTORY_GET_FAIL = 'ACCESS_HISTORY_GET_FAIL';

export const REPORT_USER = 'REPORT_USER';
export const REPORT_USER_SUCCESS = 'REPORT_USER_SUCCESS';
export const REPORT_USER_FAIL = 'REPORT_USER_FAIL';

export const CHECKOUT_USER = 'CHECKOUT_USER';
export const CHECKOUT_USER_SUCCESS = 'CHECKOUT_USER_SUCCESS';
export const CHECKOUT_USER_FAIL = 'CHECKOUT_USER_FAIL';

export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL';

export const REPORTS_ID_DELETE = 'REPORTS_ID_DELETE';
export const REPORTS_ID_DELETE_SUCCESS = 'REPORTS_ID_DELETE_SUCCESS';
export const REPORTS_ID_DELETE_FAIL = 'REPORTS_ID_DELETE_FAIL';

export const CLEAR_EVENTS = 'CLEAR_EVENTS';
